#language: node_js
#node_js:
#  - 12
services:
  - docker

before_install:
  - docker build -t andicirjaliu/docker_complex_client_test -f ./client/Dockerfile.dev ./client

script:
  - docker run andicirjaliu/docker_complex_client_test npm run test -- --coverage --watchAll=false

after_success:
  - docker build -t andicirjaliu/docker_complex_client ./client
  - docker build -t andicirjaliu/docker_complex_nginx ./nginx
  - docker build -t andicirjaliu/docker_complex_server ./server
  - docker build -t andicirjaliu/docker_complex_worker ./worker
  #Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take these images and push them to Docker hub
  - docker push andicirjaliu/docker_complex_client
  - docker push andicirjaliu/docker_complex_nginx
  - docker push andicirjaliu/docker_complex_server
  - docker push andicirjaliu/docker_complex_worker